import { useState } from "react";
import { Button } from "@/components/ui/button";

export default function WorkoutWizard({ onBack }: Readonly<{ onBack: () => void }>) {
  const [form, setForm] = useState({
    gender: "",
    days: "",
    goal: "",
    experience: "",
  });
  const [submitted, setSubmitted] = useState(false);

  const questions = [
    {
      key: "gender",
      title: "Your Gender",
      options: ["Male", "Female", "Other"],
    },
    {
      key: "days",
      title: "Training Days/Week",
      options: ["2", "3", "4", "5", "6"],
    },
    {
      key: "goal",
      title: "Training Goal",
      options: ["Build muscle", "Lose fat", "General fitness"],
    },
    {
      key: "experience",
      title: "Training Level",
      options: ["Beginner", "Intermediate", "Advanced"],
    },
  ];

  const isComplete = Object.values(form).every(Boolean);

  if (submitted) {
    return (
      <div className="space-y-4 text-center animate-fadeIn">
        <h2 className="text-xl font-bold">
          Your Custom Training Plan Overview
        </h2>
        <p className="text-sm opacity-80">
          (Soon this will be generated by AI 🧠)
        </p>
        <pre className="bg-gray-100 p-4 rounded-xl text-left text-sm">
          {JSON.stringify(form, null, 2)}
        </pre>
        <Button onClick={onBack}>Back</Button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <h2 className="text-xl font-bold">Workout Questions</h2>
      {questions.map((q) => (
        <div key={q.key} className="space-y-2">
          <div className="font-semibold">{q.title}</div>
          <div className="grid grid-cols-2 gap-2">
            {q.options.map((opt) => (
              <Button
                key={opt}
                variant={
                  form[q.key as keyof typeof form] === opt
                    ? "default"
                    : "outline"
                }
                onClick={() => setForm({ ...form, [q.key]: opt })}
              >
                {opt}
              </Button>
            ))}
          </div>
        </div>
      ))}
      <Button
        className="w-full"
        disabled={!isComplete}
        onClick={() => setSubmitted(true)}
      >
        Generate Workout Plan
      </Button>
    </div>
  );
}
