import { useState } from "react";
import { useNavigate } from "react-router-dom";

import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { X } from "lucide-react";

// Entry Component that will be triggered when user clicks "Start your journey"
export default function FitnessOnboarding() {
  const [step, setStep] = useState<"choose" | "workout" | "diet">("choose");
  const navigate = useNavigate();

  return (
    <div className="min-h-screen flex items-center justify-center p-6 bg-gray-50 relative">
      <Card className="w-full max-w-xl shadow-xl relative">
        <button
          onClick={() => navigate("/")}
          className="absolute right-3 top-3 bg-white/80 backdrop-blur-md rounded-full p-2 shadow hover:scale-110 active:scale-95 transition-all duration-200 hover:bg-black cursor-pointer "
        >
          <X className="w-4 h-4 text-black hover:text-white" />
        </button>
        <CardContent className="p-8 space-y-6">
          {step === "choose" && <ChoosePath onSelect={setStep} />}
          {step === "workout" && (
            <WorkoutWizard onBack={() => setStep("choose")} />
          )}
          {step === "diet" && <DietWizard onBack={() => setStep("choose")} />}
        </CardContent>
      </Card>
    </div>
  );
}

function ChoosePath({
  onSelect,
}: {
  onSelect: (v: "workout" | "diet") => void;
}) {
  return (
    <div className="space-y-4 text-center">
      <h1 className="text-2xl font-bold">What do you want to start with?</h1>
      <Button
        className="w-full text-lg py-6 "
        onClick={() => onSelect("workout")}
      >
        Workout Plan
      </Button>
      <Button className="w-full text-lg py-6" onClick={() => onSelect("diet")}>
        Diet Plan
      </Button>
    </div>
  );
}

// ✅ WORKOUT FLOW
function WorkoutWizard({ onBack }: { onBack: () => void }) {
  const [form, setForm] = useState({
    gender: "",
    days: "",
    goal: "",
    experience: "",
  });
  const [submitted, setSubmitted] = useState(false);

  const questions = [
    {
      key: "gender",
      title: "Your Gender",
      options: ["Male", "Female", "Other"],
    },
    {
      key: "days",
      title: "How many days can you train per week?",
      options: ["2", "3", "4", "5", "6"],
    },
    {
      key: "goal",
      title: "Training Goal",
      options: ["Build muscle", "Lose fat", "General fitness"],
    },
    {
      key: "experience",
      title: "Training Level",
      options: ["Beginner", "Intermediate", "Advanced"],
    },
  ];

  const isComplete = Object.values(form).every(Boolean);

  if (submitted) {
    return (
      <div className="space-y-4 text-center animate-fadeIn">
        <h2 className="text-xl font-bold">
          Your Custom Training Plan Overview
        </h2>
        <p className="text-sm opacity-80">
          (Soon this will be generated by AI 🧠)
        </p>
        <pre className="bg-gray-100 p-4 rounded-xl text-left text-sm">
          {JSON.stringify(form, null, 2)}
        </pre>
        <Button onClick={onBack}>Back</Button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <h2 className="text-xl font-bold">Workout Questions</h2>
      {questions.map((q) => (
        <div key={q.key} className="space-y-2">
          <div className="font-semibold">{q.title}</div>
          <div className="grid grid-cols-2 gap-2">
            {q.options.map((opt) => (
              <Button
                key={opt}
                variant={
                  form[q.key as keyof typeof form] === opt
                    ? "default"
                    : "outline"
                }
                onClick={() => setForm({ ...form, [q.key]: opt })}
              >
                {opt}
              </Button>
            ))}
          </div>
        </div>
      ))}
      <Button
        className="w-full"
        disabled={!isComplete}
        onClick={() => setSubmitted(true)}
      >
        Generate Workout Plan
      </Button>
    </div>
  );
}

// ✅ DIET FLOW
function DietWizard({ onBack }: { onBack: () => void }) {
  const [goal, setGoal] = useState("");
  const [food, setFood] = useState("");
  const [submitted, setSubmitted] = useState(false);

  if (submitted) {
    return (
      <div className="space-y-4 text-center animate-fadeIn">
        <h2 className="text-xl font-bold">Your Diet Summary</h2>
        <p className="text-sm opacity-80">
          (AI will analyze these inputs soon)
        </p>
        <pre className="bg-gray-100 p-4 rounded-xl text-left text-sm">
          {JSON.stringify({ goal, food }, null, 2)}
        </pre>
        <Button onClick={onBack}>Back</Button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <h2 className="text-xl font-bold">Diet Questions</h2>
      <div className="space-y-2">
        <div className="font-semibold">Primary Goal</div>
        <div className="grid grid-cols-2 gap-2">
          {["Body Recomposition", "Lose Fat", "Build Muscle"].map((opt) => (
            <Button
              key={opt}
              variant={goal === opt ? "default" : "outline"}
              onClick={() => setGoal(opt)}
            >
              {opt}
            </Button>
          ))}
        </div>
      </div>

      <div className="space-y-2">
        <div className="font-semibold">What do you currently eat in a day?</div>
        <textarea
          className="w-full border  p-3 min-h-[120px] focus:outline-none"
          placeholder="List your daily meals..."
          value={food}
          onChange={(e) => setFood(e.target.value)}
        />
      </div>

      <Button
        className="w-full"
        disabled={!goal || !food.trim()}
        onClick={() => setSubmitted(true)}
      >
        Submit Diet Info
      </Button>
    </div>
  );
}
